// BASE
export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";
export const LOADING = "LOADING";
export const LOADING_ALERT = "LOADING_ALERT";
export const ERROR = "ERROR";
export const SUCCESS = "SUCCESS";
export const SUCCESS_NO_MESSAGE = "SUCCESS_NO_MESSAGE";
export const HANDLE_CHANGE = "HANDLE_CHANGE";

// AUTH
export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

// PAPER
export const CLEAR_VALUES = "CLEAR_VALUES";
export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const CHANGE_VIEW = "CHANGE_VIEW";

export const AUTHOR_PAPER = "AUTHOR_PAPER";
export const CLEAR_PAPER_VALUES = "CLEAR_PAPER_VALUES";
export const SET_EDIT_PAPER = "SET_EDIT_PAPER";
export const PAPER_DETAIL = "PAPER_DETAIL";

export const CREATE_PAPER_SUCCESS = "CREATE_PAPER_SUCCESS";
export const CREATE_PAPER_ERROR = "CREATE_PAPER_ERROR";

export const EDIT_PAPER_SUCCESS = "EDIT_PAPER_SUCCESS";
export const EDIT_PAPER_ERROR = "EDIT_PAPER_ERROR";

export const SEARCH_RESULT = "SEARCH_RESULT";
export const HANDLE_AUTHOR_CHANGE = "HANDLE_AUTHOR_CHANGE";

// MEMBER
export const HANDLE_MEMBER_CHANGE = "HANDLE_MEMBER_CHANGE";

// REVIEWER
export const INVITATION = "INVITATION";
export const REVIEW_REPORT = "REVIEW_REPORT";
export const SET_EDIT_REVIEW = "SET_EDIT_REVIEW";
export const CLEAR_REVIEW_VALUES = "CLEAR_REVIEW_VALUES";
export const HANDLE_REVIEWER_CHANGE = "HANDLE_REVIEWER_CHANGE";