from sql_generator import *

account = AccountSql()
field = FieldSql()
journal = JournalSql()
paper = PaperSql()
invitation = InvitationSql()
reviewer_field = ReviewerFieldSql()
review_report = ReviewReportSql()
issue = IssueSql()

account.insert_account()
account.insert_manager()
account.insert_admin()
journal.insert()
paper.insert()
invitation.insert()
review_report.insert()
reviewer_field.insert()
issue.insert()

with open("DATA.sql", "w") as file:
    file.write("USE eJournal_DB\n\n")
    file.write(account.build())
    file.write(account.author.build())
    file.write(account.reviewer.build())
    file.write(field.build())
    file.write(reviewer_field.build())
    file.write(journal.build())
    file.write(journal.journal_field.build())
    file.write(journal.manager.build())
    file.write(paper.build())
    file.write(paper.paper_field.build())
    file.write(invitation.build())
    file.write(review_report.build())
    file.write(issue.build())
    file.write(issue.publish.build())
